# Generated by Django 2.2.7 on 2019-11-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191128_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
