# Generated by Django 2.2.7 on 2019-12-01 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ad_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='item',
        ),
        migrations.AddField(
            model_name='ad',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.Profile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
