# Generated by Django 2.2.7 on 2019-12-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191201_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
