# Generated by Django 2.2.7 on 2019-12-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ad_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['time']},
        ),
    ]
