# Generated by Django 2.2.7 on 2019-12-03 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191202_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='reciver_profile',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender_profile',
        ),
        migrations.AddField(
            model_name='message',
            name='reciver_profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reciver_messages', to='core.Profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='related_ad',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_ad', to='core.Ad'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender_messages', to='core.Profile'),
        ),
    ]
