# Generated by Django 2.2.7 on 2019-12-08 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191208_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='related_ad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_ad', to='core.Ad'),
        ),
    ]
